//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgencyBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionTeam
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string WorkArea { get; set; }
        public string FBLink { get; set; }
        public string InstaLink { get; set; }
        public string LinkedinLink { get; set; }
    }
}
